### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by aldo123** [beyonic/beyonic-python#13]
Hello, When i try to install the package I run this issue.

Collecting beyonic
  Using cached beyonic-0.1.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Aldo\AppData\Local\Temp\pip-build-4og9vlog\beyonic\setup.py", line 4, in <module>
        import beyonic
      File "C:\Users\Aldo\AppData\Local\Temp\pip-build-4og9vlog\beyonic\beyonic\__init__.py", line 13, in <module>
        from beyonic.apis.payment import Payment
      File "C:\Users\Aldo\AppData\Local\Temp\pip-build-4og9vlog\beyonic\beyonic\apis\payment.py", line 1, in <module>
        from beyonic.apis.abstract_api import AbstractAPI
      File "C:\Users\Aldo\AppData\Local\Temp\pip-build-4og9vlog\beyonic\beyonic\apis\abstract_api.py", line 1, in <module>
        from beyonic.api_client import ApiClient
      File "C:\Users\Aldo\AppData\Local\Temp\pip-build-4og9vlog\beyonic\beyonic\api_client.py", line 72
        except TypeError, e:
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Aldo\AppData\Local\Temp\pip-build-4og9vlog\beyonic\

**Comment by KayLuke** [comment]
What version of python are you installing it on?

**Comment by aldo123** [comment]
beyonic-0.1.11

**Comment by KayLuke** [comment]
The package only supports python 2.X at the moment.

**Comment by aldo123** [comment]
So what happens to someone running python 3?

**Comment by savioabuga** [comment]
1. Use [virtualenv](https://virtualenv.pypa.io/en/stable/) to create a python 2 isolated environment in your computer and install the package in the env.

2. You don't have to use the Beyonic python package. You can make requests to app.beyonic.com/api using an HTTP requests library like [Python Requests](http://docs.python-requests.org/en/master/) by following [the code examples given under the tab CURL](https://apidocs.beyonic.com/?shell) and continue using python 3.

**Comment by aldo123** [comment]
Thanks for  response, I will use send option maybe python requests. 

 

How do I get a sandbox account, I must have missed it on the documentation.
