### ISSUE TITLE
Syntax error on installation via pip

### ISSUE THREAD

**Issue by EdwardOkech** [beyonic/beyonic-python#16]
When installing via pip the installation fails due to a syntax error.
```Collecting beyonic
  Downloading https://files.pythonhosted.org/packages/3b/23/ae90ada35050a3c0cd89552c55bd55570016d4e0634b8c9f88aca7a371bb/beyonic-0.1.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v7hn288n/beyonic/setup.py", line 4, in <module>
        import beyonic
      File "/tmp/pip-install-v7hn288n/beyonic/beyonic/__init__.py", line 13, in <module>
        from beyonic.apis.payment import Payment
      File "/tmp/pip-install-v7hn288n/beyonic/beyonic/apis/payment.py", line 1, in <module>
        from beyonic.apis.abstract_api import AbstractAPI
      File "/tmp/pip-install-v7hn288n/beyonic/beyonic/apis/abstract_api.py", line 1, in <module>
        from beyonic.api_client import ApiClient
      File "/tmp/pip-install-v7hn288n/beyonic/beyonic/api_client.py", line 72
        except TypeError, e:
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-v7hn288n/beyonic/```

**Comment by KayLuke** [comment]
What version of python are you testing with?

**Comment by wizGipsBrian** [comment]
I tried using `pip install beyonic` in my python3 project and got the same error. But after cloning and adding the beyonic app to my project. after installation i just tweaked the syntax of **exception handling** .
instead of `except TypeError, e:` i used **except TypeError as e:**

**Comment by KayLuke** [comment]
Our pypi release don't officially support python 3 yet. There's a branch
that has python 3 support that you might want to consider using if you're
using python 3.
ᐧ

**Comment by wizGipsBrian** [comment]
In the node he makes changes to the exception handling as well form `except Exception, e:` to **`except Exception as e:`**. need more time to go through his code though but thanks.
Quick one, when is the official python 3 compatible package going to be dropping.

**Comment by KayLuke** [comment]
It'll probably be a merge of the python 3 branch once it's gotten a few
people using it.
ᐧ

**Comment by TiernanKennedy** [comment]
@wizGipsBrian we are using the Python3 branch in production and all has been going well. Feel free to send over any questions you may have. All conversions were done with the recommended Python3 syntax

**Comment by wizGipsBrian** [comment]
Thanks for the feedback @TiernanKennedy let me try it out.

**Comment by raybesiga** [comment]
I am facing this issue as well. How did you go about using this on a Python 3 project in production @TiernanKennedy

**Comment by raybesiga** [comment]
> @wizGipsBrian we are using the Python3 branch in production and all has been going well. Feel free to send over any questions you may have. All conversions were done with the recommended Python3 syntax

How did you reference in your requirements file @TiernanKennedy

**Comment by wizGipsBrian** [comment]
> > @wizGipsBrian we are using the Python3 branch in production and all has been going well. Feel free to send over any questions you may have. All conversions were done with the recommended Python3 syntax
> 
> How did you reference in your requirements file @TiernanKennedy

Are you getting the error at installation and which python version are you using?

**Comment by raybesiga** [comment]
hi @wizGipsBrian I am using Python 3.7.2 on MacOS Mojave. Here is the traceback:

```bash
remote: Traceback (most recent call last):
remote:   File "manage.py", line 10, in <module>
remote:     execute_from_command_line(sys.argv)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
remote:     utility.execute()
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
remote:     self.fetch_command(subcommand).run_from_argv(self.argv)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
remote:     self.execute(*args, **cmd_options)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
remote:     self.check()
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
remote:     include_deployment_checks=include_deployment_checks,
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 60, in _run_checks
remote:     issues.extend(super()._run_checks(**kwargs))
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
remote:     return checks.run_checks(**kwargs)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
remote:     new_errors = check(app_configs=app_configs)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
remote:     all_namespaces = _load_all_namespaces(resolver)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
remote:     url_patterns = getattr(resolver, 'url_patterns', [])
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
remote:     res = instance.__dict__[self.name] = self.func(instance)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
remote:     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
remote:     res = instance.__dict__[self.name] = self.func(instance)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
remote:     return import_module(self.urlconf_name)
remote:   File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
remote:     return _bootstrap._gcd_import(name[level:], package, level)
remote:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
remote:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
remote:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
remote:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
remote:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
remote:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
remote:   File "/app/saleor/urls.py", line 19, in <module>
remote:     from .order.urls import urlpatterns as order_urls
remote:   File "/app/saleor/order/urls.py", line 3, in <module>
remote:     from . import views
remote:   File "/app/saleor/order/views.py", line 21, in <module>
remote:     from ..payment.gateways.beyonic_gateway import beyonic_get_response
remote:   File "/app/saleor/payment/gateways/beyonic_gateway/__init__.py", line 5, in <module>
remote:     import beyonic
remote: ModuleNotFoundError: No module named 'beyonic'
remote: Waiting for release.... failed
```

**Comment by wizGipsBrian** [comment]
**

> "ModuleNotFoundError: No module named 'beyonic'"

**
Just need to confirm but do u have beyonic in your installed apps.

**Comment by raybesiga** [comment]
I see what you mean @wizGipsBrian 

In my requirements file, I have this:

```bash
git+https://github.com/beyonic/beyonic-python/archive/python3.zip
```
When I run `pip install -r requirements.txt` it throws this exception:

```bash
(soqonee) raymaun@Rays-MacBook-Pro:~/Projects/soqoni-web (master*%=) % pip install -r requirements.txt
Looking in indexes: https://pypi.python.org/simple
Collecting git+https://github.com/beyonic/beyonic-python/archive/python3.zip (from -r requirements.txt (line 7))
  Cloning https://github.com/beyonic/beyonic-python/archive/python3.zip to /private/var/folders/sz/dq_kmv1s22s9q399k11r2t280000gn/T/pip-req-build-mjp5fbgu
remote: Not Found
fatal: repository 'https://github.com/beyonic/beyonic-python/archive/python3.zip/' not found
Command "git clone -q https://github.com/beyonic/beyonic-python/archive/python3.zip /private/var/folders/sz/dq_kmv1s22s9q399k11r2t280000gn/T/pip-req-build-mjp5fbgu" failed with error code 128 in None
```
So it is quite likely it is not. Earlier I had used this in the requirements file:

```
git+https://github.com/jjmutumi/beyonic-python.git#beyonic3
```
And it seemed to work but I wanted to try with the official branch. Please advise.

**Comment by wizGipsBrian** [comment]
Why not try and clone the repository into your project instead and add it to your project setting?

**Comment by KayLuke** [comment]
I'd try dropping the "git+" from the URL in your requirements file so that
it's just downloading a zip file via http, not trying to clone the whole
repo.

Try: https://github.com/beyonic/beyonic-python/archive/python3.zip

- Luke.


ᐧ

**Comment by raybesiga** [comment]
Eventually what worked was that I added this to `requirements.txt`

```
git+https://github.com/beyonic/beyonic-python.git@193145acf40c6b515f79637d7a0d51ba60080fb9#egg=beyonic
```
And then run `pipenv install -r requirements.txt` so as to update the `Pipfile.lock` which triggers the build update in the Heroku buildpack. Thanks everyone for the support.

**Comment by raybesiga** [comment]
Eventually what worked was that I added this to `requirements.txt`

```
git+https://github.com/beyonic/beyonic-python.git@193145acf40c6b515f79637d7a0d51ba60080fb9#egg=beyonic
```
And then run `pipenv install -r requirements.txt` so as to update the `Pipfile.lock` which triggers the build update in the Heroku buildpack. Thanks everyone for the support.

**Comment by TiernanKennedy** [comment]
@raybesiga sorry about the delay. I built a new version of this and hosted in a private Pypi instance.

However I've been using this code in production for months and there are no major issues to report.

**Comment by raybesiga** [comment]
Noted. Thanks.

**Comment by raybesiga** [comment]
Hi @TiernanKennedy did you encounter the missing metadata bug with the Python 3 library? Something like this:

<img width="584" alt="Screenshot 2019-03-09 at 15 52 11" src="https://user-images.githubusercontent.com/405697/55315832-cab0c500-5475-11e9-89d7-e47d81313115.png">

**Comment by KayLuke** [comment]
Strange. We'll look into it. In the meantime, could enter a placeholder in
the metadata field?
ᐧ

**Comment by raybesiga** [comment]
@KayLuke Noted. Will plug.

**Comment by adfayed** [comment]
Try using 
`sudo pip2 install -r requirements.txt
`
Worked for me
